# some useful config
unsetopt BEEP
setopt interactive_comments
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line
# Useful Functions
source "$ZDOTDIR/zsh-functions"
# Normal files to source
zsh_add_file "zsh-vim-mode"
zsh_add_file "zsh-aliases"
zsh_add_file "zsh-prompt"
export TERMINAL=/usr/bin/kitty
source /usr/share/nvm/nvm.sh
source /usr/share/nvm/bash_completion
source /usr/share/nvm/install-nvm-exec
[ -z "$NVM_DIR" ] && export NVM_DIR="$XDG_DATA_HOME"/nvm --no-use
export WORKON_HOME=$XDG_DATA_HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
source ~/.local/bin/virtualenvwrapper.sh
